In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3,4],dtype='int16')
a

array([1, 2, 3, 4], dtype=int16)

In [4]:
b=np.array([[2.0,5.6,7.8],[3.0,6.7,8.9]])
b

array([[2. , 5.6, 7.8],
       [3. , 6.7, 8.9]])

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
c=np.array([b,b])
c

array([[[2. , 5.6, 7.8],
        [3. , 6.7, 8.9]],

       [[2. , 5.6, 7.8],
        [3. , 6.7, 8.9]]])

In [8]:
c.ndim

3

In [9]:
c.shape

(2, 2, 3)

In [10]:
a.shape

(4,)

In [11]:
b.shape

(2, 3)

In [12]:
c.dtype


dtype('float64')

In [13]:
a.dtype

dtype('int16')

In [14]:
a.itemsize

2

In [15]:
print(a.nbytes)
a.size*a.itemsize

8


8

In [16]:
print(b.itemsize)
b.nbytes

8


48

In [17]:
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
arr[0,-4]

4

In [19]:
arr[1,5]


13

In [20]:
arr[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[:,4]

array([ 5, 12])

In [22]:
arr[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
arr[:,2]

array([ 3, 10])

In [24]:
arr[0,1:5]

array([2, 3, 4, 5])

In [25]:
arr[1,-4:5]

array([11, 12])

In [26]:
arr[1,4]=69

In [27]:
arr[:,2]=arr[1,4]
print(arr)

[[ 1  2 69  4  5  6  7]
 [ 8  9 69 11 69 13 14]]


In [28]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
b[0,1,1]

4

In [31]:
b[0,0,0]

1

In [32]:
b[0,:]

array([[1, 2],
       [3, 4]])

In [35]:
b[1,0:1,0]

array([5])

In [37]:
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [38]:
 np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [42]:
np.full((2,2),69)

array([[69, 69],
       [69, 69]])

In [51]:
np.full_like(b,2)

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [60]:
np.random.rand(1,2,1)

array([[[0.04949312],
        [0.27267452]]])

In [64]:
np.random.random_sample(c.shape)

array([[[0.41723474, 0.88465507, 0.16747743],
        [0.2359391 , 0.78933853, 0.33890733]],

       [[0.60892521, 0.28438675, 0.19896213],
        [0.80263558, 0.50842538, 0.49138368]]])

In [69]:
np.random.randint(-11,10,size=(10,10))


array([[ -7,  -6, -11,   8,  -5,   1,   7,   4,  -9,  -3],
       [  0,  -9,  -8,   1, -11,   8,  -2, -11,   7,   5],
       [  4,  -3,  -4,  -1,  -5,  -5,   2,  -3,   8,  -9],
       [  4,   9,  -3,   2, -10,  -8,   8,  -6,   9,   2],
       [ -8,   5,   8,   7,   5,   8,  -3,   3,   5, -10],
       [ -1,   7,   6,  -8,   7,   6,  -1, -11,  -7,  -8],
       [ -3,  -8,  -5,  -5,  -1,  -6,   8, -11,   0,   8],
       [ -8,  -3,   9,   2,  -7, -11,   9,   4,   7,   8],
       [  5,   3,  -4,   8, -10,   8,   3,   3,  -6,   5],
       [  4,  -4,  -6,   0,  -9,   8,   6,  -2,   8,  -3]])

In [70]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [71]:
abc=np.array([6,7,8])
np.repeat(abc,3,axis=0)

array([6, 6, 6, 7, 7, 7, 8, 8, 8])

In [73]:
abc=np.array([[6,7,8]])
np.repeat(abc,3,axis=0)

array([[6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

In [76]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [85]:
a=np.array([1,2,3])
b=a.copy()
print(a)
print(b)

[1 2 3]
[1 2 3]


In [86]:
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [87]:
a+2

array([3, 4, 5])

In [88]:
a-2

array([-1,  0,  1])

In [89]:
a*2

array([2, 4, 6])

In [90]:
a+2-3*5

array([-12, -11, -10])

In [91]:
a+a

array([2, 4, 6])

In [92]:
a*a/a

array([1., 2., 3.])

In [93]:
a+b

array([101,   4,   6])

In [94]:
a-b

array([-99,   0,   0])

In [95]:
a*b

array([100,   4,   9])

In [96]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [97]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [98]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [99]:
a=np.ones((2,3))

In [100]:
b=np.full((3,2),2)


In [102]:
print(a)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [103]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [104]:
stats=np.array([[1,2,3],[4,5,6]])

In [105]:
np.min(stats)

1

In [106]:
np.max(stats)


6

In [107]:
np.sum(stats)

21

In [108]:
np.mean(stats)


3.5

In [109]:
np.median(stats)

3.5

In [113]:
abc=np.array([[1,2,3,4],[5,6,7,8]])

In [114]:
print(abc)

[[1 2 3 4]
 [5 6 7 8]]


In [123]:
cba=abc.reshape(1,1,8)
cba

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [135]:
v1=np.array([[1,2,3,4],[12,13,14,15]])
v2=np.array([[5,6,7,8],[15,16,16,15]])
np.vstack([v1,v2,v2,v1])

array([[ 1,  2,  3,  4],
       [12, 13, 14, 15],
       [ 5,  6,  7,  8],
       [15, 16, 16, 15],
       [ 5,  6,  7,  8],
       [15, 16, 16, 15],
       [ 1,  2,  3,  4],
       [12, 13, 14, 15]])

In [136]:
np.hstack([v1,v2,v2,v1])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  5,  6,  7,  8,  1,  2,  3,  4],
       [12, 13, 14, 15, 15, 16, 16, 15, 15, 16, 16, 15, 12, 13, 14, 15]])